version: '3'

services:
  app:  # API
    image: template-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - mysql
  mysql:  # MySQL
    image: mysql:8.0.27
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin: # phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 8888:80
volumes:
  mysql-data: